// <auto-generated />
namespace SleepLogASP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewPersonalizedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewPersonalizedData));
        
        string IMigrationMetadata.Id
        {
            get { return "201711292004274_NewPersonalizedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
